# Generated by Django 2.0.4 on 2018-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Email',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='From',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='To',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='Type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='requirements',
            field=models.CharField(max_length=3),
        ),
    ]
