# Generated by Django 2.0.4 on 2018-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180419_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='From',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='To',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='Type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='adults',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='children',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='requirements',
            field=models.CharField(max_length=40),
        ),
    ]
